import Phaser from 'phaser';
import { GLASS_SHAPES } from '../glassShapes.js';
import { CLIENT_PREFERENCES } from '../clientPreferences.js';
import { BEER_STYLES } from '../beerStyles.js';
import {
  buildClientAtlas,
  COMMON_CHARACTERS,
  ALL_CHARACTERS,
  STATES,
  FRAME_W,
  FRAME_H,
  clientTextureKey,
} from '../clientSpriteSheet.js';
import { BACKGROUNDS, BG_W, BG_H, BACK_W, BACK_H, bgTextureKey, bgBackTextureKey } from '../backgrounds.js';

// Back-compat shim — some legacy code still imports CLIENT_VARIANTS to count
// the available common variants. Re-export it from the sprite sheet module so
// the canonical source of truth lives there.
export const CLIENT_VARIANTS = COMMON_CHARACTERS;

/**
 * Generates all pixel-art textures procedurally so the game ships with
 * zero external assets. Each texture is drawn at its natural pixel size
 * and scaled up by `spriteScale` when used as a sprite.
 */
export default class BootScene extends Phaser.Scene {
  constructor() {
    super('BootScene');
  }

  preload() {
    // Per-character/per-state PNG strips — generated by
    // `node scripts/build-sprite-sheet.js`. Layout on disk:
    //   public/sprites/clients/<charId>/<state>.png
    // Each PNG is a horizontal strip of FRAMES_PER_STATE frames. Loaded as
    // Phaser spritesheets so animations index by frame number.
    // If any file is missing, buildClientAtlas() falls back to drawing the
    // corresponding strip procedurally into an in-memory canvas.
    for (const char of ALL_CHARACTERS) {
      for (const state of STATES) {
        this.load.spritesheet(
          clientTextureKey(char.id, state),
          `sprites/clients/${char.id}/${state}.png`,
          { frameWidth: FRAME_W, frameHeight: FRAME_H },
        );
      }
    }
    // Pre-rendered glass outlines — generated by `npm run glass-sprites`.
    // BootScene.create() uses these frames as the source images for each
    // glass texture key (`glass_<shape.key>`); falls back to runtime
    // drawing via makeGlassShape() if the atlas didn't load.
    this.load.atlas('glasses_atlas', 'sprites/glasses.png', 'sprites/glasses.json');
    // Pre-rendered chat bubble — generated by `npm run chat-bubble`.
    // If missing, makeChatBubble() falls back to drawing it procedurally.
    this.load.image('chat_bubble', 'sprites/chat_bubble.png');
    // Per-level backgrounds — generated by `npm run backgrounds`.
    //   bg.png   = upper customer-side wall (1920×370)
    //   back.png = back-bar wall behind the taps (1920×530)
    // Missing files fall back to runtime drawing in create().
    for (const bg of BACKGROUNDS) {
      this.load.image(bgTextureKey(bg.id), `sprites/backgrounds/${bg.id}/bg.png`);
      if (bg.drawBack) {
        this.load.image(bgBackTextureKey(bg.id), `sprites/backgrounds/${bg.id}/back.png`);
      }
    }
  }

  create() {
    this.makePixel('foam', 0xfff4d6);
    this.makePixel('shadow', 0x000000);

    // Per-beer tap textures (idle + active) and matching stream textures.
    BEER_STYLES.forEach((style) => {
      this.makeTap(`tap_${style.key}`, false, style);
      this.makeTap(`tap_${style.key}_active`, true, style);
      this.makeStream(`stream_${style.key}`, style);
    });
    // Generic fallbacks (used by anything that doesn't pass a beer style).
    this.makeTap('tap', false, BEER_STYLES[0]);
    this.makeTap('tap_active', true, BEER_STYLES[0]);
    this.makeStream('stream', BEER_STYLES[0]);
    this.makePixel('beer_fill', 0xf2b330);

    // 8 glass shape outline textures, keyed `glass_<shape.key>`.
    // Prefer the prebuilt atlas (`npm run glass-sprites`) so we ship a
    // hand-editable PNG; if the atlas is missing, fall back to runtime drawing.
    const atlasReady =
      this.textures.exists('glasses_atlas') &&
      GLASS_SHAPES.every((s) => this.textures.get('glasses_atlas').has(`glass_${s.key}`));
    if (atlasReady) {
      this.registerGlassesFromAtlas();
    } else {
      GLASS_SHAPES.forEach((shape) => this.makeGlassShape(shape));
    }
    // Back-compat key — first shape doubles as the legacy `glass_empty`.
    if (!this.textures.exists('glass_empty')) {
      const first = GLASS_SHAPES[0];
      this.textures.addImage('glass_empty', this.textures.get(`glass_${first.key}`).getSourceImage());
    }

    // Client sprite-sheet atlas — one row per character, columns covering
    // every animation state (idle, normal, antsy, furious, talking_left/right)
    // with FRAMES_PER_STATE frames each. Also registers Phaser animations.
    buildClientAtlas(this);

    // Speech bubble background for the "wants this beer" indicator.
    // Prefer the prebuilt PNG (`npm run chat-bubble`) — skip the runtime
    // draw if it loaded correctly. Otherwise fall back to drawing it
    // procedurally so the game still works.
    if (!this.chatBubbleLoaded('chat_bubble')) {
      this.makeChatBubble('chat_bubble');
    }

    // Background textures — if any failed to preload (PNG missing), render
    // them procedurally into an in-memory canvas. Detects failure by checking
    // the source image dimensions match the expected BG_W × BG_H.
    for (const bg of BACKGROUNDS) {
      // Customer-side wall
      const key = bgTextureKey(bg.id);
      const ok = this.textures.exists(key)
        && this.textures.get(key).getSourceImage()?.width === BG_W
        && this.textures.get(key).getSourceImage()?.height === BG_H;
      if (!ok) {
        const c = document.createElement('canvas');
        c.width = BG_W; c.height = BG_H;
        const cx = c.getContext('2d');
        cx.imageSmoothingEnabled = false;
        bg.draw(cx, 0, 0);
        if (this.textures.exists(key)) this.textures.remove(key);
        this.textures.addCanvas(key, c);
      }

      // Back-bar wall (if this background defines one)
      if (bg.drawBack) {
        const bkey = bgBackTextureKey(bg.id);
        const bok = this.textures.exists(bkey)
          && this.textures.get(bkey).getSourceImage()?.width === BACK_W
          && this.textures.get(bkey).getSourceImage()?.height === BACK_H;
        if (!bok) {
          const c = document.createElement('canvas');
          c.width = BACK_W; c.height = BACK_H;
          const cx = c.getContext('2d');
          cx.imageSmoothingEnabled = false;
          bg.drawBack(cx, 0, 0);
          if (this.textures.exists(bkey)) this.textures.remove(bkey);
          this.textures.addCanvas(bkey, c);
        }
      }
    }

    // Client-preference icons — one per (pref × beer style) combo so the
    // icon liquid color matches the desired beer.
    CLIENT_PREFERENCES.forEach((pref) => {
      BEER_STYLES.forEach((style) => this.makePreferenceIcon(pref, style));
    });

    this.scene.start('MenuScene');
  }

  // 1x1 pixel of a flat color — stretched at runtime for fills/streams.
  makePixel(key, color) {
    const g = this.add.graphics();
    g.fillStyle(color, 1);
    g.fillRect(0, 0, 1, 1);
    g.generateTexture(key, 1, 1);
    g.destroy();
  }

  // Beer stream — 4×16 px tile, designed to scroll vertically as a TileSprite.
  // Columns: dark edge | body | bright specular | light edge.
  // Rows: a repeating pattern of body/foam bands so when the tile scrolls
  // downward it reads as flowing liquid with droplets and air pockets.
  makeStream(key, style) {
    const W = 4;
    const H = 16;
    const body = style.liquidColor;
    const edgeDark = darken(style.liquidColor, 0.65);
    const edgeBright = style.key === 'stout' ? 0x6a3a20 : 0xfff4d6;
    const bubble = style.key === 'stout' ? 0xa67050 : 0xfff4d6;

    const g = this.add.graphics();

    // Base body fill across the whole tile
    g.fillStyle(body, 1);
    g.fillRect(0, 0, W, H);

    // Side columns (dark left edge, soft right edge) — gives the stream
    // depth and a clear silhouette against any background.
    g.fillStyle(edgeDark, 1);
    g.fillRect(0, 0, 1, H);
    g.fillStyle(edgeBright, 0.45);
    g.fillRect(W - 1, 0, 1, H);

    // Specular streak — interrupted column so the highlight reads as
    // moving when the tile scrolls.
    for (let y = 0; y < H; y++) {
      if (y % 4 !== 3) {
        g.fillStyle(edgeBright, 0.8);
        g.fillRect(1, y, 1, 1);
      }
    }

    // Droplet / air pocket pattern — periodic dark notch + a bright
    // single-pixel highlight just below it. Repeats every 8px.
    for (let y = 2; y < H; y += 8) {
      g.fillStyle(edgeDark, 0.8);
      g.fillRect(2, y, 1, 1);
      g.fillStyle(bubble, 0.9);
      g.fillRect(2, y + 1, 1, 1);
    }

    g.generateTexture(key, W, H);
    g.destroy();
  }

  // Tap: dark wooden top, metal body, spout. 24x40 px.
  // The handle (lever) takes the beer style's handle color so each tap
  // can be visually distinguished from the others.
  makeTap(key, active, style) {
    const w = 24;
    const h = 40;
    const g = this.add.graphics();

    // Palette
    const woodDark = 0x2a1f14;
    const wood = 0x4a3724;
    const woodLight = 0x6b4f33;
    const woodEdge = 0x8a6a40;
    const metalShadow = 0x4a4a52;
    const metalBase = 0x8a8a92;
    const metalLight = 0xc4c4cc;
    const metalBright = 0xeaeaef;
    const spoutDark = 0x3a3a42;
    const spout = 0x6a6a72;
    const handleBase = style.handleColor;
    const handleBright = style.handleHighlight;
    const handleDark = darken(handleBase, 0.6);
    const handleTop = active ? lighten(handleBright, 1.2) : handleBright;

    // --- Wall mount plate (back of tap) ---
    // Outline + two-tone wood face + 2 visible bolt heads.
    g.fillStyle(woodDark, 1);
    g.fillRect(1, 0, w - 2, 7); // outline plate
    g.fillStyle(wood, 1);
    g.fillRect(2, 1, w - 4, 5); // main face
    g.fillStyle(woodLight, 1);
    g.fillRect(3, 1, w - 6, 1); // top highlight strip
    g.fillStyle(woodDark, 1);
    g.fillRect(2, 5, w - 4, 1); // bottom shadow strip
    // Bolts
    g.fillStyle(woodEdge, 1);
    g.fillRect(4, 3, 1, 1);
    g.fillRect(w - 5, 3, 1, 1);
    g.fillStyle(metalLight, 1);
    g.fillRect(4, 3, 1, 1);
    g.fillStyle(woodDark, 1);
    g.fillRect(4, 4, 1, 1); // bolt shadow
    g.fillStyle(metalLight, 1);
    g.fillRect(w - 5, 3, 1, 1);
    g.fillStyle(woodDark, 1);
    g.fillRect(w - 5, 4, 1, 1);

    // --- Main chrome body — tapered, with proper specular streak ---
    // Wider at the top (just under the mount), slightly narrower at the
    // spout shoulder. Drawn row-by-row so we can taper cleanly.
    const bodyTop = 7;
    const bodyBot = 28;
    for (let y = bodyTop; y < bodyBot; y++) {
      const t = (y - bodyTop) / (bodyBot - bodyTop - 1); // 0..1
      // Body half-width: 6 at top → 5 near the bottom shoulder.
      const half = t < 0.85 ? 6 : 5;
      const cx = w / 2;
      // Outline
      g.fillStyle(metalShadow, 1);
      g.fillRect(cx - half, y, 1, 1);
      g.fillRect(cx + half - 1, y, 1, 1);
      // Body fill
      g.fillStyle(metalBase, 1);
      g.fillRect(cx - half + 1, y, half * 2 - 2, 1);
    }
    // Specular streak (left-of-center) — runs the body's length, brighter in
    // the middle to look cylindrical.
    for (let y = bodyTop + 1; y < bodyBot - 1; y++) {
      g.fillStyle(metalLight, 1);
      g.fillRect(8, y, 1, 1);
      // Center brightest pixel cluster
      if (y > 11 && y < 22) {
        g.fillStyle(metalBright, 1);
        g.fillRect(9, y, 1, 1);
      }
    }
    // Right-side soft shadow column
    for (let y = bodyTop + 1; y < bodyBot - 1; y++) {
      g.fillStyle(metalShadow, 0.6);
      g.fillRect(w - 9, y, 1, 1);
    }
    // Decorative collar rings — two thin bands across the body for that
    // segmented chrome look.
    const ringYs = [11, 22];
    for (const ry of ringYs) {
      g.fillStyle(metalShadow, 1);
      g.fillRect(7, ry, w - 14, 1);
      g.fillStyle(metalBright, 1);
      g.fillRect(7, ry - 1, w - 14, 1);
    }

    // --- Handle (knob) — taller, with a rounded ball top ---
    // Stem (rectangular)
    const stemX = 10;
    const stemY = 2;
    const stemW = 4;
    const stemH = 7;
    g.fillStyle(handleDark, 1);
    g.fillRect(stemX, stemY, stemW, stemH); // base
    g.fillStyle(handleBase, 1);
    g.fillRect(stemX, stemY, stemW - 1, stemH); // main stem
    g.fillStyle(handleBright, 1);
    g.fillRect(stemX, stemY, 1, stemH); // left highlight column
    // Ball top — slightly wider than the stem
    const ballY = stemY - 2;
    g.fillStyle(handleDark, 1);
    g.fillRect(stemX - 1, ballY + 1, stemW + 2, 1); // bottom row (widest)
    g.fillRect(stemX, ballY, stemW, 1); // top row
    g.fillStyle(handleBase, 1);
    g.fillRect(stemX, ballY + 1, stemW, 1);
    g.fillRect(stemX - 1, ballY + 1, 1, 1);
    g.fillRect(stemX + stemW, ballY + 1, 1, 1);
    g.fillStyle(handleTop, 1);
    g.fillRect(stemX + 1, ballY, 2, 1); // ball top highlight
    // Sparkle on the ball
    g.fillStyle(0xffffff, 1);
    g.fillRect(stemX + 1, ballY, 1, 1);
    // Stem→body collar ring
    g.fillStyle(handleDark, 1);
    g.fillRect(stemX - 1, stemY + stemH, stemW + 2, 1);

    // --- Spout — angled-looking with a rim and a dark inner hole ---
    const spoutTop = 28;
    // Shoulder under the body (a bit wider than the spout itself)
    g.fillStyle(metalShadow, 1);
    g.fillRect(6, spoutTop, w - 12, 1);
    g.fillStyle(metalLight, 1);
    g.fillRect(7, spoutTop, w - 14, 1);
    // Spout body
    g.fillStyle(spout, 1);
    g.fillRect(8, spoutTop + 1, w - 16, 5);
    // Spout highlight column
    g.fillStyle(metalLight, 1);
    g.fillRect(8, spoutTop + 1, 1, 4);
    // Spout shadow column
    g.fillStyle(spoutDark, 1);
    g.fillRect(w - 9, spoutTop + 1, 1, 4);
    // Rim under the spout
    g.fillStyle(metalShadow, 1);
    g.fillRect(7, spoutTop + 6, w - 14, 1);
    // Dark inner hole at the very bottom
    g.fillStyle(spoutDark, 1);
    g.fillRect(9, spoutTop + 6, w - 18, 2);
    g.fillStyle(0x1a1a1f, 1);
    g.fillRect(10, spoutTop + 7, w - 20, 1);

    // --- Active state — warm glow around the body + a beer-colored drip ---
    if (active) {
      // Warm glow on the upper body
      g.fillStyle(0xfff4d6, 0.35);
      g.fillRect(7, bodyTop, w - 14, 2);
      // Beer-tinted glow inside the spout opening
      g.fillStyle(style.liquidColor, 0.7);
      g.fillRect(10, spoutTop + 7, w - 20, 1);
      // Tiny drip clinging to the spout edge
      g.fillStyle(style.liquidColor, 1);
      g.fillRect(11, spoutTop + 8, 2, 1);
      g.fillStyle(style.liquidEdgeColor, 1);
      g.fillRect(11, spoutTop + 8, 1, 1);
    }

    g.generateTexture(key, w, h);
    g.destroy();
  }

  /**
   * Glass outline driven by a shape's width profile. Drawn at 2× native
   * pixel density (versus the original tiny sprites), so the rim, base,
   * handle and stem all get multi-pixel bevels and richer highlights.
   *
   * Layers (outside → inside):
   *   - 1px dark outer outline (slight blue-grey)
   *   - 1px lighter "edge" column inside the outline (cool reflection)
   *   - 2-column specular streak on the upper-left (bright + dim)
   *   - 1-column inner shadow on the right (curvature cue)
   * Rim is 3 rows tall: outer dark, bright lip, inner shadow.
   * Base is 3 rows tall: contact line, soft shadow, ground shadow.
   * Handle / stem / foot use 2-3px walls so they read as actual glassware.
   */
  /**
   * Copy each glass frame from the prebuilt atlas into its own standalone
   * texture so the rest of the code can keep using `glass_<shape.key>` as
   * a top-level texture key (rather than knowing about the atlas).
   */
  registerGlassesFromAtlas() {
    const atlas = this.textures.get('glasses_atlas');
    const source = atlas.getSourceImage();
    for (const shape of GLASS_SHAPES) {
      const key = `glass_${shape.key}`;
      if (this.textures.exists(key)) continue;
      const frameName = `glass_${shape.key}`;
      const frame = atlas.frames[frameName];
      if (!frame) continue;
      const cw = frame.width;
      const ch = frame.height;
      const canvasTex = this.textures.createCanvas(key, cw, ch);
      canvasTex.context.imageSmoothingEnabled = false;
      canvasTex.context.drawImage(
        source,
        frame.cutX, frame.cutY, cw, ch,
        0, 0, cw, ch,
      );
      canvasTex.refresh();
    }
  }

  makeGlassShape(shape) {
    const W = shape.outerWidthPx;
    const H = shape.outerHeightPx;
    const innerH = shape.innerHeightPx;
    const innerW = shape.innerWidthPx;
    const innerTop = shape.topPaddingPx;
    const innerBottom = H - shape.bottomPaddingPx;
    const cx = Math.floor(W / 2);

    // Layered glass palette — outline, an inner cool-reflection column, a
    // bright rim, a brighter specular highlight, and two shadow tones for
    // the inside of the glass and the table contact.
    const outline = 0x7a9bbf;
    const outlineDark = 0x4a6a8a;
    const wallEdge = 0xa6c2dd; // cool reflective tint just inside the outline
    const rim = 0xeaf6ff;
    const highlight = 0xffffff;
    const innerShadow = 0x8fb2d4;
    const innerShadowDeep = 0x6b94b8;
    const baseShadow = 0x5f7d9a;

    const g = this.add.graphics();

    // Precompute halfPx per inner row so we can index neighbours when
    // anti-stepping the outline (avoid 1px gaps when the profile changes
    // by more than 1 column between adjacent rows).
    const halfByRow = new Array(innerH);
    for (let y = 0; y < innerH; y++) {
      const t = 1 - y / (innerH - 1);
      const widthFrac = Math.max(0, Math.min(1, shape.widthProfile(t)));
      halfByRow[y] = Math.max(1, Math.round((innerW * widthFrac) / 2));
    }

    // --- Side walls ---
    for (let y = 0; y < innerH; y++) {
      const halfPx = halfByRow[y];
      const rowY = innerTop + y;

      // Outer outline columns
      g.fillStyle(outline, 1);
      g.fillRect(cx - halfPx - 1, rowY, 1, 1);
      g.fillRect(cx + halfPx, rowY, 1, 1);

      // Inner "edge" column — a slightly brighter tint sitting against
      // the outline, gives the wall a touch of glass-thickness.
      if (halfPx >= 3 && y > 1 && y < innerH - 2) {
        g.fillStyle(wallEdge, 0.7);
        g.fillRect(cx + halfPx - 1, rowY, 1, 1);
      }

      // Fill in diagonal step gaps so the outline reads as continuous
      // even when the profile narrows/widens quickly.
      if (y > 0) {
        const prev = halfByRow[y - 1];
        const diff = halfPx - prev;
        if (diff > 1) {
          g.fillStyle(outline, 1);
          for (let k = 1; k < diff; k++) {
            g.fillRect(cx - prev - 1 - k, rowY, 1, 1);
            g.fillRect(cx + prev + k, rowY, 1, 1);
          }
        } else if (diff < -1) {
          g.fillStyle(outline, 1);
          for (let k = 1; k < -diff; k++) {
            g.fillRect(cx - prev - 1 + k, rowY - 1, 1, 1);
            g.fillRect(cx + prev - k, rowY - 1, 1, 1);
          }
        }
      }

      // Specular streak — a 2-column bright highlight on the upper-left.
      // The bright column sits one pixel inside the wall; a softer dim
      // column sits one further in. Fades near the rim and base.
      if (y > 2 && y < innerH - 3) {
        // Fade strength near the ends so the streak doesn't bleed into rim/base.
        const fadeTop = Math.min(1, (y - 2) / 6);
        const fadeBot = Math.min(1, (innerH - 3 - y) / 6);
        const fade = Math.min(fadeTop, fadeBot);
        g.fillStyle(highlight, 0.65 * fade);
        g.fillRect(cx - halfPx, rowY, 1, 1);
        if (halfPx >= 5) {
          g.fillStyle(highlight, 0.25 * fade);
          g.fillRect(cx - halfPx + 1, rowY, 1, 1);
        }
        // A brighter "core" pixel cluster mid-height adds a glint.
        if (y > innerH * 0.25 && y < innerH * 0.55) {
          g.fillStyle(highlight, 0.9 * fade);
          g.fillRect(cx - halfPx, rowY, 1, 1);
        }
      }

      // Inner shadow — soft tint on the right interior to suggest curvature.
      if (y > 1 && y < innerH - 2 && halfPx >= 3) {
        g.fillStyle(innerShadow, 0.5);
        g.fillRect(cx + halfPx - 2, rowY, 1, 1);
        // Deeper shadow column on the very inside of the right wall, near
        // the bottom third (where light pools in real glass).
        if (y > innerH * 0.55 && halfPx >= 4) {
          g.fillStyle(innerShadowDeep, 0.4);
          g.fillRect(cx + halfPx - 3, rowY, 1, 1);
        }
      }
    }

    // --- Top rim — elliptical opening so the cup reads as 3D ---
    // See src/glassSpriteSheet.js for the row-by-row breakdown — keep
    // these two implementations in sync.
    const topHalf = halfByRow[0];
    const cavityHalf = Math.max(1, Math.min(topHalf - 2, Math.floor(topHalf * 0.6)));

    if (topHalf >= 4 && cavityHalf >= 1) {
      g.fillStyle(innerShadowDeep, 0.85);
      g.fillRect(cx - cavityHalf, innerTop - 4, cavityHalf * 2, 1);
    }
    if (topHalf >= 4) {
      g.fillStyle(outline, 1);
      g.fillRect(cx - cavityHalf - 1, innerTop - 3, cavityHalf * 2 + 2, 1);
    }

    g.fillStyle(outline, 1);
    g.fillRect(cx - topHalf - 2, innerTop - 2, 1, 1);
    g.fillRect(cx + topHalf + 1, innerTop - 2, 1, 1);
    if (topHalf >= 4) {
      const shoulderL = cx - cavityHalf - 1;
      const shoulderR = cx + cavityHalf + 1;
      const leftEnd = cx - topHalf - 1;
      const rightEnd = cx + topHalf;
      if (shoulderL > leftEnd) g.fillRect(leftEnd, innerTop - 2, shoulderL - leftEnd, 1);
      if (shoulderR < rightEnd) g.fillRect(shoulderR + 1, innerTop - 2, rightEnd - shoulderR, 1);
    } else {
      g.fillRect(cx - topHalf - 1, innerTop - 3, topHalf * 2 + 2, 1);
    }
    g.fillStyle(rim, 1);
    g.fillRect(cx - topHalf, innerTop - 2, topHalf * 2, 1);

    g.fillStyle(outline, 1);
    g.fillRect(cx - topHalf - 1, innerTop - 1, 1, 1);
    g.fillRect(cx + topHalf, innerTop - 1, 1, 1);
    g.fillStyle(rim, 0.85);
    g.fillRect(cx - topHalf, innerTop - 1, topHalf * 2, 1);

    g.fillStyle(highlight, 1);
    g.fillRect(cx - topHalf + 1, innerTop - 2, Math.min(2, topHalf), 1);
    if (topHalf >= 4) {
      g.fillRect(cx - Math.floor(cavityHalf / 2), innerTop - 3, Math.min(3, cavityHalf), 1);
    }

    g.fillStyle(innerShadow, 0.7);
    g.fillRect(cx + topHalf - Math.min(3, topHalf), innerTop - 1, Math.min(3, topHalf), 1);

    // --- Bottom — thick base with proper bevel + ground shadow ---
    const botHalf = halfByRow[innerH - 1];
    // Contact line (outer outline along the bottom).
    g.fillStyle(outline, 1);
    g.fillRect(cx - botHalf - 1, innerBottom, botHalf * 2 + 2, 1);

    if (!shape.stem && innerBottom + 1 < H - 1) {
      // Beveled base: a soft shadow row, then a darker ground shadow.
      g.fillStyle(baseShadow, 0.7);
      g.fillRect(cx - botHalf, innerBottom + 1, botHalf * 2, 1);
      g.fillStyle(baseShadow, 0.45);
      if (innerBottom + 2 < H) {
        g.fillRect(cx - botHalf, innerBottom + 2, botHalf * 2, 1);
      }
      // Wider outer "ground shadow" — slightly wider, dimmer strip
      if (innerBottom + 3 < H) {
        g.fillStyle(outlineDark, 0.35);
        g.fillRect(cx - botHalf - 1, innerBottom + 3, botHalf * 2 + 2, 1);
      }
      // Tiny dark "weight" pixels at the base corners.
      g.fillStyle(outlineDark, 0.6);
      g.fillRect(cx - botHalf - 1, innerBottom + 1, 1, 1);
      g.fillRect(cx + botHalf, innerBottom + 1, 1, 1);
    }

    // --- Optional handle (mug/stein) — thicker D-shape with thumb rest ---
    if (shape.handle) {
      const hxStart = cx + botHalf + 1;
      const hyTop = innerTop + Math.floor(innerH * 0.22);
      const hyBot = innerTop + Math.floor(innerH * 0.72);
      const hxEnd = Math.min(W - 1, hxStart + 10);
      const armThick = 3;

      // Top arm — 3px thick wedge
      g.fillStyle(outline, 1);
      for (let t = 0; t < armThick; t++) {
        g.fillRect(hxStart, hyTop + t, hxEnd - hxStart + 1 - t, 1);
      }
      // Bottom arm — mirror of top
      for (let t = 0; t < armThick; t++) {
        g.fillRect(hxStart, hyBot - t, hxEnd - hxStart + 1 - t, 1);
      }
      // Outer arc (the curve of the D) — 2px thick
      g.fillRect(hxEnd, hyTop, 1, hyBot - hyTop + 1);
      g.fillRect(hxEnd - 1, hyTop + 1, 1, hyBot - hyTop - 1);

      // Bright highlight running down the outer curve (upper portion).
      g.fillStyle(rim, 0.8);
      g.fillRect(hxEnd, hyTop + 1, 1, Math.max(1, Math.floor((hyBot - hyTop) / 3)));
      g.fillStyle(highlight, 1);
      g.fillRect(hxEnd, hyTop + 2, 1, 2);

      // Soft thumb-rest indent on the inside of the top arm.
      const thumbY = hyTop + armThick + 1;
      const thumbX = hxStart + Math.floor((hxEnd - hxStart) * 0.35);
      g.fillStyle(outlineDark, 0.7);
      g.fillRect(thumbX, thumbY, 3, 1);
      g.fillStyle(innerShadow, 0.5);
      g.fillRect(thumbX, thumbY + 1, 3, 1);

      // Inner shadow on the inside of the handle (depth).
      g.fillStyle(outlineDark, 0.55);
      g.fillRect(hxStart, hyBot, 2, 1);
      g.fillRect(hxStart, hyTop, 2, 1);
    }

    // --- Optional stem + foot (goblet) — multi-pixel stem with bead + flared foot ---
    if (shape.stem) {
      const stemTop = innerBottom + 1;
      const stemBot = H - 5;
      const stemHalf = 3;

      // Stem body — 6px wide with outline columns + inner fill
      g.fillStyle(outline, 1);
      g.fillRect(cx - stemHalf, stemTop, stemHalf * 2, stemBot - stemTop);
      // Stem highlight (left column) — 2px wide gradient
      g.fillStyle(highlight, 0.8);
      g.fillRect(cx - stemHalf, stemTop, 1, stemBot - stemTop);
      g.fillStyle(rim, 0.6);
      g.fillRect(cx - stemHalf + 1, stemTop, 1, stemBot - stemTop);
      // Stem shadow (right column)
      g.fillStyle(outlineDark, 0.65);
      g.fillRect(cx + stemHalf - 1, stemTop, 1, stemBot - stemTop);

      // Decorative bead at upper-third and lower-third of the stem.
      const beadYs = [
        stemTop + Math.floor((stemBot - stemTop) * 0.3),
        stemTop + Math.floor((stemBot - stemTop) * 0.65),
      ];
      for (const beadY of beadYs) {
        g.fillStyle(outline, 1);
        g.fillRect(cx - stemHalf - 1, beadY, stemHalf * 2 + 2, 1);
        g.fillRect(cx - stemHalf - 1, beadY + 1, stemHalf * 2 + 2, 1);
        g.fillStyle(rim, 0.85);
        g.fillRect(cx - stemHalf, beadY, 2, 1);
        g.fillStyle(outlineDark, 0.5);
        g.fillRect(cx + stemHalf - 2, beadY + 1, 2, 1);
      }

      // Foot — flared base with a bright top edge and ground shadow.
      const footHalf = Math.floor(W * 0.34);
      // Top edge of foot (curves up slightly toward the stem).
      g.fillStyle(outline, 1);
      g.fillRect(cx - footHalf, H - 4, footHalf * 2, 1);
      g.fillRect(cx - footHalf, H - 3, footHalf * 2, 1);
      // Bright top of the foot.
      g.fillStyle(rim, 0.9);
      g.fillRect(cx - footHalf + 1, H - 4, footHalf * 2 - 2, 1);
      g.fillStyle(highlight, 1);
      g.fillRect(cx - footHalf + 2, H - 4, Math.min(4, footHalf * 2 - 4), 1);
      // Bottom row — ground contact shadow.
      g.fillStyle(outlineDark, 0.7);
      g.fillRect(cx - footHalf, H - 2, footHalf * 2, 1);
      g.fillStyle(outlineDark, 0.4);
      g.fillRect(cx - footHalf - 1, H - 1, footHalf * 2 + 2, 1);
    }

    g.generateTexture(`glass_${shape.key}`, W, H);
    g.destroy();
  }


  /**
   * Speech bubble background for the preference icon. Cream-white fill,
   * dark outline, rounded corners (corners knocked off pixel-style), with
   * a small downward-pointing tail at the bottom-left. Sized to wrap the
   * 18x20 preference icon with a 1px padding margin.
   */
  /**
   * True if the chat bubble PNG loaded correctly. Phaser silently creates
   * a placeholder when an image 404s, so we check the source image size
   * against the expected 28×28 to detect that case.
   */
  chatBubbleLoaded(key) {
    if (!this.textures.exists(key)) return false;
    const src = this.textures.get(key).getSourceImage();
    return src && src.width === 28 && src.height === 28;
  }

  makeChatBubble(key) {
    const W = 28;
    const H = 28; // 22 bubble + 6 tail
    const bubbleH = 22;
    const fill = 0xfff4d6;
    const fillLight = 0xffffff;
    const outline = 0x2a1f14;
    const shadow = 0xd9c89a;

    const g = this.add.graphics();

    // Solid fill (rounded by knocking out the 4 corner pixels after).
    g.fillStyle(fill, 1);
    g.fillRect(1, 1, W - 2, bubbleH - 2);

    // Outline (top, bottom, left, right). Skip the 4 corner pixels for round look.
    g.fillStyle(outline, 1);
    g.fillRect(2, 0, W - 4, 1); // top
    g.fillRect(2, bubbleH - 1, W - 4, 1); // bottom
    g.fillRect(0, 2, 1, bubbleH - 4); // left
    g.fillRect(W - 1, 2, 1, bubbleH - 4); // right
    // corner step pixels (one in, one down from each corner)
    g.fillRect(1, 1, 1, 1);
    g.fillRect(W - 2, 1, 1, 1);
    g.fillRect(1, bubbleH - 2, 1, 1);
    g.fillRect(W - 2, bubbleH - 2, 1, 1);

    // Inner top highlight (gives the bubble a glossy plastic feel).
    g.fillStyle(fillLight, 1);
    g.fillRect(2, 1, W - 4, 1);
    g.fillRect(1, 2, 1, 1);
    g.fillRect(W - 2, 2, 1, 1);

    // Inner bottom shadow.
    g.fillStyle(shadow, 1);
    g.fillRect(2, bubbleH - 2, W - 4, 1);

    // Tail — pointing down-left toward the speaker. Outline + fill.
    // Triangle approximated by stacked rects, tip at (5, bubbleH + 5).
    g.fillStyle(outline, 1);
    g.fillRect(6, bubbleH, 5, 1);
    g.fillRect(5, bubbleH + 1, 5, 1);
    g.fillRect(4, bubbleH + 2, 4, 1);
    g.fillRect(3, bubbleH + 3, 3, 1);
    g.fillRect(3, bubbleH + 4, 2, 1);
    g.fillRect(3, bubbleH + 5, 1, 1);
    // Fill inside the tail
    g.fillStyle(fill, 1);
    g.fillRect(7, bubbleH, 3, 1);
    g.fillRect(6, bubbleH + 1, 3, 1);
    g.fillRect(5, bubbleH + 2, 2, 1);
    g.fillRect(4, bubbleH + 3, 1, 1);
    // Erase the outline pixels that sit right under where the tail meets
    // the bubble so the join reads as continuous interior.
    g.fillStyle(fill, 1);
    g.fillRect(6, bubbleH - 1, 4, 1);

    g.generateTexture(key, W, H);
    g.destroy();
  }

  /**
   * Preference icon — a mini glass silhouette filled to the desired liquid
   * level with a foam cap of the desired thickness on top. 18x20 px.
   * The liquid color matches the beer style the client wants.
   */
  makePreferenceIcon(pref, style) {
    const W = 18;
    const H = 20;
    const g = this.add.graphics();

    // Glass outline (a simple straight-sided mug).
    const outline = 0xe8d9a8;
    const left = 4;
    const right = W - 5;
    const top = 2;
    const bottom = H - 2;

    g.fillStyle(outline, 1);
    g.fillRect(left, top, 1, bottom - top);            // left side
    g.fillRect(right, top, 1, bottom - top);           // right side
    g.fillRect(left, bottom, right - left + 1, 1);     // bottom
    g.fillRect(left, top, right - left + 1, 1);        // top rim

    // Inner usable area for liquid + foam
    const innerLeft = left + 1;
    const innerRight = right - 1;
    const innerTop = top + 1;
    const innerBottom = bottom - 1;
    const innerW = innerRight - innerLeft + 1;
    const innerH = innerBottom - innerTop + 1;

    // Desired liquid height in inner pixels (based on fillTarget %)
    const liquidPx = Math.max(1, Math.round((pref.fill.fillTarget / 100) * innerH));
    // Desired foam height in inner pixels (foam ratio relative to liquid, clamped to room left)
    const foamRoomPx = innerH - liquidPx;
    const foamPxIdeal = Math.round((pref.foam.foamRatioTarget / 100) * liquidPx);
    const foamPx = Math.min(foamRoomPx, foamPxIdeal);

    // Beer — colored to match the requested beer style.
    if (liquidPx > 0) {
      const beerY = innerBottom - liquidPx + 1;
      g.fillStyle(style.liquidColor, 1);
      g.fillRect(innerLeft, beerY, innerW, liquidPx);
      g.fillStyle(style.liquidEdgeColor, 1);
      g.fillRect(innerLeft, beerY, 1, liquidPx);
      g.fillRect(innerRight, beerY, 1, liquidPx);
    }

    // Foam (cream cap with one bubble highlight) — same for all beers for readability.
    if (foamPx > 0) {
      const foamY = innerBottom - liquidPx - foamPx + 1;
      g.fillStyle(0xfff4d6, 1);
      g.fillRect(innerLeft, foamY, innerW, foamPx);
      g.fillStyle(0xe6d6a8, 1);
      g.fillRect(innerLeft, foamY, 1, foamPx);
      g.fillRect(innerRight, foamY, 1, foamPx);
      // A bubble dot
      g.fillStyle(0xffffff, 1);
      g.fillRect(innerLeft + Math.floor(innerW / 2), foamY, 1, 1);
    } else {
      // "no foam" indicator — a thin dashed bar above the liquid
      const flatY = innerBottom - liquidPx;
      g.fillStyle(0xe6d6a8, 0.7);
      g.fillRect(innerLeft, flatY, 2, 1);
      g.fillRect(innerLeft + 4, flatY, 2, 1);
      g.fillRect(innerLeft + 8, flatY, 2, 1);
    }

    g.generateTexture(`${pref.iconKey}_${style.key}`, W, H);
    g.destroy();
  }
}

function darken(color, factor) {
  const r = Math.floor(((color >> 16) & 0xff) * factor);
  const g = Math.floor(((color >> 8) & 0xff) * factor);
  const b = Math.floor((color & 0xff) * factor);
  return (r << 16) | (g << 8) | b;
}

function lighten(color, factor) {
  const r = Math.min(255, Math.floor(((color >> 16) & 0xff) * factor));
  const g = Math.min(255, Math.floor(((color >> 8) & 0xff) * factor));
  const b = Math.min(255, Math.floor((color & 0xff) * factor));
  return (r << 16) | (g << 8) | b;
}

