// Loader + animation registry for the client sprites.
//
// Disk layout (generated by `node scripts/build-sprite-sheet.js`):
//   public/sprites/clients/manifest.json     ← character + state list
//   public/sprites/clients/<charId>/<state>.png  ← 6-frame horizontal strip
//
// Each PNG is loaded into Phaser as a **spritesheet** (auto-sliced grid)
// under the texture key `clients_<charId>_<state>`. Animations are
// registered with the key `<charId>_<state>` (unchanged from before so
// the rest of the game keeps working).
//
// The Client object uses `body.play(animKey)` to drive animations, which
// transparently switches between the per-state textures behind the scenes.

import { ARCHETYPES } from './clientArchetypes.js';

export const FRAME_W = 192;
export const FRAME_H = 264;

export const STATES = ['idle', 'normal', 'antsy', 'furious', 'talking_left', 'talking_right', 'walking'];
export const FRAMES_PER_STATE = 6;

export const STATE_ANIM = {
  idle: { frameRate: 6, repeat: -1 },
  normal: { frameRate: 8, repeat: -1 },
  antsy: { frameRate: 12, repeat: -1 },
  furious: { frameRate: 16, repeat: -1 },
  talking_left: { frameRate: 12, repeat: -1 },
  talking_right: { frameRate: 12, repeat: -1 },
  walking: { frameRate: 14, repeat: -1 },
};

export const COMMON_CHARACTERS = ARCHETYPES.filter((a) => !a.special);
export const SPECIAL_CHARACTERS = ARCHETYPES.filter((a) => a.special);
export const ALL_CHARACTERS = ARCHETYPES;

const SPECIAL_SPAWN_CHANCE = 0.1;

export function pickCharacter() {
  if (SPECIAL_CHARACTERS.length > 0 && Math.random() < SPECIAL_SPAWN_CHANCE) {
    return SPECIAL_CHARACTERS[Math.floor(Math.random() * SPECIAL_CHARACTERS.length)];
  }
  if (COMMON_CHARACTERS.length === 0) return SPECIAL_CHARACTERS[0];
  return COMMON_CHARACTERS[Math.floor(Math.random() * COMMON_CHARACTERS.length)];
}

/** Texture key for a single per-state spritesheet. */
export function clientTextureKey(charId, state) {
  return `clients_${charId}_${state}`;
}

/** Animation key (unchanged from previous version). */
export function animKey(charId, state) {
  return `${charId}_${state}`;
}

/**
 * Returns the texture key that should be used to display the first frame
 * of a given (character, state). Convenience wrapper so callers don't have
 * to know about the per-state spritesheet split.
 */
export function clientFirstFrameTexture(charId, state) {
  return clientTextureKey(charId, state);
}

// Per-character drawing dispatcher — used by the offline build script.
// Kept exported so scripts/build-sprite-sheet.js can paint each strip.
export function drawClientFrame(ctx, ox, oy, char, state, frameIdx) {
  if (!char || !char.draw) {
    console.warn('drawClientFrame: missing draw function for char', char);
    return;
  }
  char.draw(ctx, ox, oy, state, frameIdx);
}

/**
 * Build / register all character animations. Two paths:
 *   1) Spritesheets were preloaded by BootScene (preferred — uses the on-disk
 *      PNGs). buildClientAtlas just registers animations against them.
 *   2) Spritesheets are missing (load failed, dev hasn't run `npm run sprites`)
 *      → fall back to drawing each frame procedurally into in-memory canvases
 *      and adding them as spritesheet textures.
 */
export function buildClientAtlas(scene) {
  for (const char of ALL_CHARACTERS) {
    for (const state of STATES) {
      const texKey = clientTextureKey(char.id, state);
      if (!scene.textures.exists(texKey) || !textureHasFrames(scene, texKey)) {
        // Fallback path: render the strip into an in-memory canvas + register
        // it as a spritesheet so the rest of the code still works.
        buildFallbackStrip(scene, char, state);
      }
      registerAnimation(scene, char.id, state);
    }
  }
}

function textureHasFrames(scene, texKey) {
  const tex = scene.textures.get(texKey);
  // Phaser's spritesheets get frames named '0', '1', ... in addition to '__BASE'.
  return tex && tex.frames && Object.keys(tex.frames).length >= FRAMES_PER_STATE;
}

function buildFallbackStrip(scene, char, state) {
  const texKey = clientTextureKey(char.id, state);
  const stripW = FRAMES_PER_STATE * FRAME_W;
  const stripH = FRAME_H;
  const canvas = document.createElement('canvas');
  canvas.width = stripW;
  canvas.height = stripH;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  for (let f = 0; f < FRAMES_PER_STATE; f++) {
    drawClientFrame(ctx, f * FRAME_W, 0, char, state, f);
  }
  if (scene.textures.exists(texKey)) {
    scene.textures.remove(texKey);
  }
  // addSpriteSheet auto-slices the canvas into FRAME_W × FRAME_H frames.
  scene.textures.addSpriteSheet(texKey, canvas, { frameWidth: FRAME_W, frameHeight: FRAME_H });
}

function registerAnimation(scene, charId, state) {
  const key = animKey(charId, state);
  if (scene.anims.exists(key)) return;
  const texKey = clientTextureKey(charId, state);
  const frames = [];
  for (let f = 0; f < FRAMES_PER_STATE; f++) {
    frames.push({ key: texKey, frame: f });
  }
  const cadence = STATE_ANIM[state];
  scene.anims.create({
    key,
    frames,
    frameRate: cadence.frameRate,
    repeat: cadence.repeat,
  });
}
